routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SambutanController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\CalonSiswaController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\EkstrakurikulerController;
use App\Http\Controllers\LogoController;
use App\Http\Controllers\PrestasiController;
use App\Http\Controllers\SaranaPrasaranaController;
use App\Http\Controllers\SejarahController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\TujuanSloganController;
use App\Http\Controllers\VisiMisiController;
use App\Http\Controllers\MediaSosialController;
use App\Http\Controllers\Api\Lokasi;
use App\Http\Controllers\BudayaController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\KetenagaanController;
use App\Http\Controllers\LokasiKontakController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\StrukturKurikulumController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');
Route::get('home', function () {
    return view('index');
})->name('home');
Route::get('/profile', function () {
    return view('profile');
})->name('profile');
Route::get('/akademik', function () {
    return view('akademik');
})->name('akademik');
Route::get('/ketenagaan', function () {
    return view('ketenagaan');
})->name('ketenagaan');
Route::get('/ketenagaan/{ketenagaan}', function () {
    return view('ketenagaan-detail');
})->name('ketenagaan.detail');
Route::get('/lokasi', function () {
    return view('lokasi');
})->name('lokasi');
Route::get('/faq', function () {
    return view('faq');
})->name('faq');
Route::get('/siswa/diterima', function () {
    return view('siswa-diterima');
})->name('siswa.diterima');

Route::get('/chat', [LokasiKontakController::class, 'chat'])->name('chat');
Route::post('/chat', [LokasiKontakController::class, 'chat_whatsapp'])->name('chat.post');
Route::get('/blog', [BlogController::class, 'blog'])->name('blog');
Route::get('/blog/{blog}', [BlogController::class, 'blog_detail'])->name('blog-detail');
Route::get('/ketenagaan/{ketenagaan}', [KetenagaanController::class, 'ketenagaan_detail'])->name('ketenagaan-detail');
Route::get('/ekstrakurikuler/{ekstrakurikuler}', [EkstrakurikulerController::class, 'ekstrakurikuler_detail'])->name('ekstrakurikuler-detail');
Route::get('/prestasi/{prestasi}', [PrestasiController::class, 'prestasi_detail'])->name('prestasi-detail');
Route::get('/saranaprasarana/{saranaprasarana}', [SaranaPrasaranaController::class, 'saranaprasarana_detail'])->name('saranaprasarana-detail');
Route::get('/jurusan/{jurusan}', [JurusanController::class, 'jurusan_detail'])->name('jurusan-detail');
Route::prefix('daftar')->group(function () {
    Route::get('hal-satu', [CalonSiswaController::class, 'createStepOne'])->name('daftar.hal.satu');
    Route::post('hal-satu', [CalonSiswaController::class, 'postCreateStepOne'])->name('daftar.hal.satu.post');
    Route::get('hal-dua', [CalonSiswaController::class, 'createStepTwo'])->name('daftar.hal.dua');
    Route::post('hal-dua', [CalonSiswaController::class, 'postCreateStepTwo'])->name('daftar.hal.dua.post');
    Route::get('hal-tiga', [CalonSiswaController::class, 'createStepThree'])->name('daftar.hal.tiga');
    Route::post('hal-tiga', [CalonSiswaController::class, 'postCreateStepThree'])->name('daftar.hal.tiga.post');
    Route::get('hal-empat', [CalonSiswaController::class, 'createStepFour'])->name('daftar.hal.empat');
    Route::post('hal-empat', [CalonSiswaController::class, 'postCreateStepFour'])->name('daftar.hal.empat.post');
    Route::get('hal-lima', [CalonSiswaController::class, 'createStepFive'])->name('daftar.hal.lima');
    Route::post('hal-lima', [CalonSiswaController::class, 'postCreateStepFive'])->name('daftar.hal.lima.post');
    Route::get('hal-enam', [CalonSiswaController::class, 'createStepSix'])->name('daftar.hal.enam');
    Route::post('hal-enam', [CalonSiswaController::class, 'postCreateStepSix'])->name('daftar.hal.enam.post');
});

Route::prefix('api')->group(function () {
    Route::post('provinsis', [Lokasi::class, 'getProvinsis'])->name('api.provinsis');
    Route::post('provinsi', [Lokasi::class, 'getProvinsi'])->name('api.provinsi');
    Route::post('domisili', [Lokasi::class, 'getDomisili'])->name('api.domisili');
});

Auth::routes();

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('logo', LogoController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('sambutan', SambutanController::class);
    Route::resource('sejarah', SejarahController::class);
    Route::resource('ekstrakurikuler', EkstrakurikulerController::class);
    Route::resource('prestasi', PrestasiController::class);
    Route::resource('ketenagaan', KetenagaanController::class);
    Route::resource('budaya', BudayaController::class);
    Route::resource('tujuan-slogan', TujuanSloganController::class);
    Route::resource('visi-misi', VisiMisiController::class);
    Route::get('calonsiswa/print/{calonsiswa}', [CalonSiswaController::class, 'print'])->name('print');
    Route::get('calonsiswa/print', [CalonSiswaController::class, 'print_calonsiswa'])->name('print.calonsiswa');
    Route::get('pendaftar-ditolak', [CalonSiswaController::class, 'indexDitolak'])->name('pendaftar.ditolak');
    Route::resource('calonsiswa', CalonSiswaController::class);
    Route::resource('siswa', SiswaController::class);
    Route::resource('sarana-prasarana', SaranaPrasaranaController::class);
    Route::resource('blog', BlogController::class);
    Route::resource('mediasosial', MediaSosialController::class);
    Route::resource('lokasikontak', LokasiKontakController::class);
    Route::resource('jurusan', JurusanController::class);
    Route::resource('pertanyaan', PertanyaanController::class);
    Route::resource('strukturkurikulum', StrukturKurikulumController::class);
});

Route::get('install', function () {
    // shell_exec('composer install');
    Artisan::call('migrate:fresh');
    Artisan::call('db:seed');
    Artisan::call('key:generate');
});

app/Http/Controllers/SiswaController.php
<?php

namespace App\Http\Controllers;

use App\Models\CalonSiswa;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class SiswaController extends Controller
{
    public function index()
    {
        $siswas = CalonSiswa::where('status_siswa', 'Diterima')->get();
        return view('siswa.index', compact('siswas'));
    }

    public function show(CalonSiswa $siswa)
    {
        return view('siswa.show', compact('siswa'));
    }

}

resources/views/siswa/index.blade.php
@extends('layouts.master', ['title' => 'Siswa', 'first' => 'Siswa'])

@section('content')
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Siswa</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <div class="panel-body">
        <table id="data-table-default" class="table table-striped table-bordered table-td-valign-middle">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Nama</th>
                    <th>NISN</th>
                    <th>Status</th>
                    <th>Aksi</th>
                </tr>
            </thead>

            <tbody>
                @foreach($siswas as $siswa)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>{{ $siswa->nama }}</td>
                    <td>{{ $siswa->nisn }}</td>
                    <td><span class="badge bg-success">{{ $siswa->status_siswa }}</span></td>
                    <td class="d-flex">
                        <a href="{{ route('siswa.show', $siswa->id) }}" class="btn btn-sm btn-info mr-1"><i class="fas fa-eye"></i></a>

                        <a href="{{ route('print', $siswa->id) }}" class="btn btn-sm btn-info mr-1"><i class="fas fa-print"></i></a>

                        <div class="dropdown mr-1">
                            <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-exclamation"></i>
                            </button>
                            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
                                <form action="{{ route('siswa.update', $siswa->id) }}" method="post">
                                    @csrf
                                    @method('PATCH')
                                    <input type="hidden" value="Ditolak" name="status_siswa">
                                    <button type="submit" class="dropdown-item" value="tolak">Tolak</button>
                                </form>
                            </div>
                        </div>

                        <form action="{{ route('siswa.destroy', $siswa->id) }}" method="post">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger mr-1" onclick="return confirm('Apakah anda yakin ingin menghapus data ini?')"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@stop

resources/views/siswa/show.blade.php
@extends('layouts.master', ['title' => 'Siswa', 'first' => 'Siswa', 'second' => 'Detail Siswa'])

@section('content')
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Siswa</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <div class="panel-body">
    <table>
        <tr>
            <td>Jalur PPDB</td>
            <td>:</td>
            <td>{{ $siswa->jalur_ppdb }}</td>
        </tr>
        <tr>
            <td>Nama</td>
            <td>:</td>
            <td>{{ $siswa->nama }}</td>
        </tr>
        <tr>
            <td>Kewarganegaraan</td>
            <td>:</td>
            <td>{{ $siswa->kewarganegaraan }}</td>
        </tr>
        <tr>
            <td>Email</td>
            <td>:</td>
            <td>{{ $siswa->email }}</td>
        </tr>
        <tr>
            <td>Nomor KK</td>
            <td>:</td>
            <td>{{ $siswa->nomor_kk }}</td>
        </tr>
        <tr>
            <td>Jurusan 1</td>
            <td>:</td>
            <td>{{ explode('-',$siswa->jurusan)[0] }}</td>
        </tr>
        <tr>
            <td>Jurusan 2</td>
            <td>:</td>
            <td>{{ explode('-',$siswa->jurusan)[1] }}</td>
        </tr>
        <tr>
            <td>Tempat Lahir</td>
            <td>:</td>
            <td>{{ $siswa->tempat_lahir }}</td>
        </tr>
        <tr>
            <td>Tanggal Lahir</td>
            <td>:</td>
            <td>{{ $siswa->tanggal_lahir }}</td>
        </tr>
        <tr>
            <td>Jenis Kelamin</td>
            <td>:</td>
            <td>{{ $siswa->jenis_kelamin }}</td>
        </tr>
        <tr>
            <td>Agama</td>
            <td>:</td>
            <td>{{ $siswa->agama }}</td>
        </tr>
        <tr>
            <td>Status Anak</td>
            <td>:</td>
            <td>{{ $siswa->status_anak }}</td>
        </tr>
        <tr>
            <td>Anak Ke</td>
            <td>:</td>
            <td>{{ $siswa->anak_ke }}</td>
        </tr>
        <tr>
            <td>Jumlah Saudara</td>
            <td>:</td>
            <td>{{ $siswa->jumlah_saudara }}</td>
        </tr>
        <tr>
            <td>Tinggi Badan</td>
            <td>:</td>
            <td>{{ $siswa->tinggi_badan }}</td>
        </tr>
        <tr>
            <td>Berat badan</td>
            <td>:</td>
            <td>{{ $siswa->berat_badan }}</td>
        </tr>
        <tr>
            <td>Golongan darah</td>
            <td>:</td>
            <td>{{ $siswa->golongan_darah }}</td>
        </tr>
        <tr>
            <td>Alamat</td>
            <td>:</td>
            <td>{{ $siswa->alamat }}</td>
        </tr>
        <tr>
            <td>RT</td>
            <td>:</td>
            <td>{{ $siswa->rt }}</td>
        </tr>
        <tr>
            <td>RW</td>
            <td>:</td>
            <td>{{ $siswa->rw }}</td>
        </tr>
        <tr>
            <td>Kelurahan</td>
            <td>:</td>
            <td>{{ $siswa->kelurahan }}</td>
        </tr>
        <tr>
            <td>Kecamatan</td>
            <td>:</td>
            <td>{{ $siswa->kecamatan }}</td>
        </tr>
        <tr>
            <td>Domisili</td>
            <td>:</td>
            <td>{{ $siswa->domisili }}</td>
        </tr>
        <tr>
            <td>Provinsi</td>
            <td>:</td>
            <td>{{ $siswa->provinsi }}</td>
        </tr>
        <tr>
            <td>Kode Pos</td>
            <td>:</td>
            <td>{{ $siswa->kode_pos }}</td>
        </tr>
        <tr>
            <td>Jarak Kesekolah</td>
            <td>:</td>
            <td>{{ $siswa->jarak_kesekolah }}</td>
        </tr>
        <tr>
            <td>Transportasi Kesekolah</td>
            <td>:</td>
            <td>{{ $siswa->transportasi_kesekolah }}</td>
        </tr>
        <tr>
            <td>Handphone</td>
            <td>:</td>
            <td>{{ $siswa->telp }}</td>
        </tr>
        <tr>
            <td>Penerima PKH</td>
            <td>:</td>
            <td>{{ $siswa->penerima_pkh }}</td>
        </tr>
        <tr>
            <td>Asal Sekolah</td>
            <td>:</td>
            <td>{{ $siswa->asal_sekolah }}</td>
        </tr>
        <tr>
            <td>Tahun Lulus</td>
            <td>:</td>
            <td>{{ $siswa->tahun_lulus }}</td>
        </tr>
        <tr>
            <td>NISN</td>
            <td>:</td>
            <td>{{ $siswa->nisn }}</td>
        </tr>
        <tr>
            <td>Nama Ayah</td>
            <td>:</td>
            <td>{{ $siswa->nama_ayah }}</td>
        </tr>
        <tr>
            <td>NIK Ayah</td>
            <td>:</td>
            <td>{{ $siswa->nik_ayah }}</td>
        </tr>
        <tr>
            <td>Alamat Ayah</td>
            <td>:</td>
            <td>{{ $siswa->nik_ayah }}</td>
        </tr>
        <tr>
            <td>NIK Ayah</td>
            <td>:</td>
            <td>{{ $siswa->alamat_ayah }}</td>
        </tr>
        <tr>
            <td>Tempat Lahir Ayah</td>
            <td>:</td>
            <td>{{ $siswa->tempat_lahir_ayah }}</td>
        </tr>
        <tr>
            <td>Tanggal Lahir Ayah</td>
            <td>:</td>
            <td>{{ $siswa->tanggal_lahir_ayah }}</td>
        </tr>
        <tr>
            <td>Agama Ayah</td>
            <td>:</td>
            <td>{{ $siswa->agama_ayah }}</td>
        </tr>
        <tr>
            <td>Pendidikan Ayah</td>
            <td>:</td>
            <td>{{ $siswa->pendidikan_ayah }}</td>
        </tr>
        <tr>
            <td>Pekerjaan Ayah</td>
            <td>:</td>
            <td>{{ $siswa->pekerjaan_ayah }}</td>
        </tr>
        <tr>
            <td>Penghasilan Ayah</td>
            <td>:</td>
            <td>{{ $siswa->penghasilan_ayah }}</td>
        </tr>
        <tr>
            <td>Telepon Ayah</td>
            <td>:</td>
            <td>{{ $siswa->telp_ayah }}</td>
        </tr>
        <tr>
            <td>Nama Ibu</td>
            <td>:</td>
            <td>{{ $siswa->nama_ibu }}</td>
        </tr>
        <tr>
            <td>NIK Ibu</td>
            <td>:</td>
            <td>{{ $siswa->nik_ibu }}</td>
        </tr>
        <tr>
            <td>Alamat Ibu</td>
            <td>:</td>
            <td>{{ $siswa->nik_ibu }}</td>
        </tr>
        <tr>
            <td>NIK Ibu</td>
            <td>:</td>
            <td>{{ $siswa->alamat_ibu }}</td>
        </tr>
        <tr>
            <td>Tempat Lahir Ibu</td>
            <td>:</td>
            <td>{{ $siswa->tempat_lahir_ibu }}</td>
        </tr>
        <tr>
            <td>Tanggal Lahir Ibu</td>
            <td>:</td>
            <td>{{ $siswa->tanggal_lahir_ibu }}</td>
        </tr>
        <tr>
            <td>Agama Ibu</td>
            <td>:</td>
            <td>{{ $siswa->agama_ibu }}</td>
        </tr>
        <tr>
            <td>Pendidikan Ibu</td>
            <td>:</td>
            <td>{{ $siswa->pendidikan_ibu }}</td>
        </tr>
        <tr>
            <td>Pekerjaan Ibu</td>
            <td>:</td>
            <td>{{ $siswa->pekerjaan_ibu }}</td>
        </tr>
        <tr>
            <td>Penghasilan Ibu</td>
            <td>:</td>
            <td>{{ $siswa->penghasilan_ibu }}</td>
        </tr>
        <tr>
            <td>Telepon Ibu</td>
            <td>:</td>
            <td>{{ $siswa->telp_ibu }}</td>
        </tr>
        <tr>
            <td>Nama Wali</td>
            <td>:</td>
            <td>{{ $siswa->nama_wali }}</td>
        </tr>
        <tr>
            <td>NIK Wali</td>
            <td>:</td>
            <td>{{ $siswa->nik_wali }}</td>
        </tr>
        <tr>
            <td>Alamat Wali</td>
            <td>:</td>
            <td>{{ $siswa->nik_wali }}</td>
        </tr>
        <tr>
            <td>NIK Wali</td>
            <td>:</td>
            <td>{{ $siswa->alamat_wali }}</td>
        </tr>
        <tr>
            <td>Tempat Lahir Wali</td>
            <td>:</td>
            <td>{{ $siswa->tempat_lahir_wali }}</td>
        </tr>
        <tr>
            <td>Tanggal Lahir Wali</td>
            <td>:</td>
            <td>{{ $siswa->tanggal_lahir_wali }}</td>
        </tr>
        <tr>
            <td>Agama Wali</td>
            <td>:</td>
            <td>{{ $siswa->agama_wali }}</td>
        </tr>
        <tr>
            <td>Pendidikan Wali</td>
            <td>:</td>
            <td>{{ $siswa->pendidikan_wali }}</td>
        </tr>
        <tr>
            <td>Pekerjaan Wali</td>
            <td>:</td>
            <td>{{ $siswa->pekerjaan_wali }}</td>
        </tr>
        <tr>
            <td>Penghasilan Wali</td>
            <td>:</td>
            <td>{{ $siswa->penghasilan_wali }}</td>
        </tr>
        <tr>
            <td>Telepon Wali</td>
            <td>:</td>
            <td>{{ $siswa->telp_wali }}</td>
        </tr>
     </table>
    </div>
</div>
@stop