routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\SambutanController;
use App\Http\Controllers\SliderController;
use App\Http\Controllers\CalonSiswaController;
use App\Http\Controllers\BlogController;
use App\Http\Controllers\EkstrakurikulerController;
use App\Http\Controllers\LogoController;
use App\Http\Controllers\PrestasiController;
use App\Http\Controllers\SaranaPrasaranaController;
use App\Http\Controllers\SejarahController;
use App\Http\Controllers\SiswaController;
use App\Http\Controllers\TujuanSloganController;
use App\Http\Controllers\VisiMisiController;
use App\Http\Controllers\MediaSosialController;
use App\Http\Controllers\Api\Lokasi;
use App\Http\Controllers\BudayaController;
use App\Http\Controllers\JurusanController;
use App\Http\Controllers\KetenagaanController;
use App\Http\Controllers\LokasiKontakController;
use App\Http\Controllers\PertanyaanController;
use App\Http\Controllers\StrukturKurikulumController;
use Illuminate\Support\Facades\Artisan;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('index');
})->name('home');
Route::get('home', function () {
    return view('index');
})->name('home');
Route::get('/profile', function () {
    return view('profile');
})->name('profile');
Route::get('/akademik', function () {
    return view('akademik');
})->name('akademik');
Route::get('/ketenagaan', function () {
    return view('ketenagaan');
})->name('ketenagaan');
Route::get('/ketenagaan/{ketenagaan}', function () {
    return view('ketenagaan-detail');
})->name('ketenagaan.detail');
Route::get('/lokasi', function () {
    return view('lokasi');
})->name('lokasi');
Route::get('/faq', function () {
    return view('faq');
})->name('faq');
Route::get('/siswa/diterima', function () {
    return view('siswa-diterima');
})->name('siswa.diterima');

Route::get('/chat', [LokasiKontakController::class, 'chat'])->name('chat');
Route::post('/chat', [LokasiKontakController::class, 'chat_whatsapp'])->name('chat.post');
Route::get('/blog', [BlogController::class, 'blog'])->name('blog');
Route::get('/blog/{blog}', [BlogController::class, 'blog_detail'])->name('blog-detail');
Route::get('/ketenagaan/{ketenagaan}', [KetenagaanController::class, 'ketenagaan_detail'])->name('ketenagaan-detail');
Route::get('/ekstrakurikuler/{ekstrakurikuler}', [EkstrakurikulerController::class, 'ekstrakurikuler_detail'])->name('ekstrakurikuler-detail');
Route::get('/prestasi/{prestasi}', [PrestasiController::class, 'prestasi_detail'])->name('prestasi-detail');
Route::get('/saranaprasarana/{saranaprasarana}', [SaranaPrasaranaController::class, 'saranaprasarana_detail'])->name('saranaprasarana-detail');
Route::get('/jurusan/{jurusan}', [JurusanController::class, 'jurusan_detail'])->name('jurusan-detail');
Route::prefix('daftar')->group(function () {
    Route::get('hal-satu', [CalonSiswaController::class, 'createStepOne'])->name('daftar.hal.satu');
    Route::post('hal-satu', [CalonSiswaController::class, 'postCreateStepOne'])->name('daftar.hal.satu.post');
    Route::get('hal-dua', [CalonSiswaController::class, 'createStepTwo'])->name('daftar.hal.dua');
    Route::post('hal-dua', [CalonSiswaController::class, 'postCreateStepTwo'])->name('daftar.hal.dua.post');
    Route::get('hal-tiga', [CalonSiswaController::class, 'createStepThree'])->name('daftar.hal.tiga');
    Route::post('hal-tiga', [CalonSiswaController::class, 'postCreateStepThree'])->name('daftar.hal.tiga.post');
    Route::get('hal-empat', [CalonSiswaController::class, 'createStepFour'])->name('daftar.hal.empat');
    Route::post('hal-empat', [CalonSiswaController::class, 'postCreateStepFour'])->name('daftar.hal.empat.post');
    Route::get('hal-lima', [CalonSiswaController::class, 'createStepFive'])->name('daftar.hal.lima');
    Route::post('hal-lima', [CalonSiswaController::class, 'postCreateStepFive'])->name('daftar.hal.lima.post');
    Route::get('hal-enam', [CalonSiswaController::class, 'createStepSix'])->name('daftar.hal.enam');
    Route::post('hal-enam', [CalonSiswaController::class, 'postCreateStepSix'])->name('daftar.hal.enam.post');
});

Route::prefix('api')->group(function () {
    Route::post('provinsis', [Lokasi::class, 'getProvinsis'])->name('api.provinsis');
    Route::post('provinsi', [Lokasi::class, 'getProvinsi'])->name('api.provinsi');
    Route::post('domisili', [Lokasi::class, 'getDomisili'])->name('api.domisili');
});

Auth::routes();

Route::prefix('dashboard')->middleware('auth')->group(function () {
    Route::get('/', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('logo', LogoController::class);
    Route::resource('slider', SliderController::class);
    Route::resource('sambutan', SambutanController::class);
    Route::resource('sejarah', SejarahController::class);
    Route::resource('ekstrakurikuler', EkstrakurikulerController::class);
    Route::resource('prestasi', PrestasiController::class);
    Route::resource('ketenagaan', KetenagaanController::class);
    Route::resource('budaya', BudayaController::class);
    Route::resource('tujuan-slogan', TujuanSloganController::class);
    Route::resource('visi-misi', VisiMisiController::class);
    Route::get('calonsiswa/print/{calonsiswa}', [CalonSiswaController::class, 'print'])->name('print');
    Route::get('calonsiswa/print', [CalonSiswaController::class, 'print_calonsiswa'])->name('print.calonsiswa');
    Route::get('pendaftar-ditolak', [CalonSiswaController::class, 'indexDitolak'])->name('pendaftar.ditolak');
    Route::resource('calonsiswa', CalonSiswaController::class);
    Route::resource('siswa', SiswaController::class);
    Route::resource('sarana-prasarana', SaranaPrasaranaController::class);
    Route::resource('blog', BlogController::class);
    Route::resource('mediasosial', MediaSosialController::class);
    Route::resource('lokasikontak', LokasiKontakController::class);
    Route::resource('jurusan', JurusanController::class);
    Route::resource('pertanyaan', PertanyaanController::class);
    Route::resource('strukturkurikulum', StrukturKurikulumController::class);
});

Route::get('install', function () {
    // shell_exec('composer install');
    Artisan::call('migrate:fresh');
    Artisan::call('db:seed');
    Artisan::call('key:generate');
});

app/Models/Blog.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Blog extends Model
{
    use HasFactory;
    protected $guarded = [];

}

app/Http/Controllers/BlogController.php
<?php

namespace App\Http\Controllers;

use App\Models\Blog;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Storage;

class BlogController extends Controller
{
    public function index()
    {
        $blogs = Blog::get();

        return view('blog.index', compact('blogs'));
    }

    public function create()
    {
        $blog = new Blog();
        $action = route('blog.store');
        $method = 'POST';

        return view('blog.form', compact('blog', 'action', 'method'));
    }

    public function store(Request $request)
    {
        $attr = $request->validate([
            'judul' => 'required',
            'deskripsi' => 'required',
            'gambar' => 'required|mimes:jpg,png,jpeg,gif'
        ]);

        try {
            DB::beginTransaction();

            $image = $request->file('gambar');
            $attr['gambar'] = $image->storeAs('images/blog', date('Ymd') . rand(1000, 9999) . '.' . $image->extension());

            Blog::create($attr);

            DB::commit();

            return redirect()->route('blog.index')->with('success', 'Blog berhasil dibuat');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function show(Blog $blog)
    {
        return view('blog.show', compact('blog'));
    }

    public function edit(Blog $blog)
    {
        $action = route('blog.update', $blog->id);
        $method = 'PATCH';

        return view('blog.form', compact('blog', 'action', 'method'));
    }

    public function update(Request $request, Blog $blog)
    {
        $attr = $request->validate([
            'judul' => 'required',
            'deskripsi' => 'required',
            'gambar' => 'mimes:jpg,png,jpeg,gif'
        ]);

        try {
            DB::beginTransaction();

            if ($request->file('gambar')) {
                Storage::delete($blog->gambar);
                $image = $request->file('gambar');
                $attr['gambar'] = $image->storeAs('images/blog', date('Ymd') . rand(1000, 9999) . '.' . $image->extension());
            } else {
                $attr['gambar'] = $blog->gambar;
            }

            $blog->update($attr);

            DB::commit();

            return redirect()->route('blog.index')->with('success', 'Blog berhasil diubah');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function destroy(Blog $blog)
    {
        try {
            DB::beginTransaction();

            Storage::delete($blog->gambar);
            $blog->delete();

            DB::commit();

            return redirect()->route('blog.index')->with('success', 'Blog berhasil dihapus');
        } catch (\Throwable $th) {
            return back()->with('error', $th->getMessage());
        }
    }

    public function blog()
    {
        return view('blog');
    }

    public function blog_detail(Blog $blog)
    {
        return view('blog-detail', compact('blog'));
    }
}

resources/views/blog/form.blade.php
@extends('layouts.master', ['title' => 'Blog', 'first' => 'Blog', 'second' => 'Buat Blog'])

@section('content')
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Blog</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <div class="panel-body">
        <form action="{{ $action }}" method="post" enctype="multipart/form-data">
            <input type="hidden" name="_method" value="{{ $method }}">
            @csrf

            <div class="form-group">
                <label for="gambar">Gambar</label>
                <input type="file" name="gambar" id="gambar" class="form-control" onchange="document.getElementById('preview').src = window.URL.createObjectURL(this.files[0])">
                <br>
                <img id="preview" alt="your gambar" width="100" src="{{ asset('storage/' . $blog->gambar) ?? '' }}" />

                @error('gambar')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>
          
            <div class="form-group">
                <label for="judul">Judul</label>
                <input type="text" name="judul" id="judul" class="form-control" value="{{ $blog->judul ?? old('judul') }}">

                @error('judul')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <label for="deskripsi">Deskipsi</label>
                <textarea id="editor" name="deskripsi">{{ $blog->deskripsi ?? old('deskripsi') }}</textarea>

                @error('deskripsi')
                <small class="text-danger">{{ $message }}</small>
                @enderror
            </div>

            <div class="form-group">
                <button type="submit" class="btn btn-primary">Kirim</button>
            </div>
        </form>
    </div>
</div>

@stop

resources/views/blog/index.blade.php
@extends('layouts.master', ['title' => 'Blog', 'first' => 'Blog'])

@section('content')
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Blog</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <div class="panel-body">
        <a href="{{ route('blog.create') }}" class="btn btn-primary mb-3">Buat Blog</a>
        <table id="data-table-default" class="table table-striped table-bordered table-td-valign-middle">
            <thead>
                <tr>
                    <th>No</th>
                    <th>Gambar</th>
                    <th>Judul</th>
                    <th>Aksi</th>
                </tr>
            </thead>

            <tbody>
                @foreach($blogs as $blog)
                <tr>
                    <td>{{ $loop->iteration }}</td>
                    <td>
                        <img src="{{ asset('storage/' . $blog->gambar) }}" alt="{{ $blog->gambar }}" width="100">
                    </td>
                    <td>{{ $blog->judul }}</td>
                    <td class="d-flex">
                        <a href="{{ route('blog.edit', $blog->id) }}" class="btn btn-sm btn-success mr-1"><i class="fas fa-edit"></i></a>
                        <a href="{{ route('blog.show', $blog->id) }}" class="btn btn-sm btn-info mr-1"><i class="fas fa-eye"></i></a>
                        <form action="{{ route('blog.destroy', $blog->id) }}" method="post">
                            @method('DELETE')
                            @csrf
                            <button type="submit" class="btn btn-danger mr-1" onclick="return confirm('Are you sure to delete this data ?')"><i class="fas fa-trash"></i></button>
                        </form>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@stop

resources/views/blog/show.blade.php
@extends('layouts.master', ['title' => 'Blog', 'first' => 'Detail Blog'])

@section('content')
<div class="panel panel-inverse">
    <div class="panel-heading">
        <h4 class="panel-title">Blog</h4>
        <div class="panel-heading-btn">
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-default" data-click="panel-expand"><i class="fa fa-expand"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-success" data-click="panel-reload"><i class="fa fa-redo"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-warning" data-click="panel-collapse"><i class="fa fa-minus"></i></a>
            <a href="javascript:;" class="btn btn-xs btn-icon btn-circle btn-danger" data-click="panel-remove"><i class="fa fa-times"></i></a>
        </div>
    </div>
    <div class="panel-body">
        <div>
            <div class="text-center">
                <h3>{{ $blog->judul }}</h3>
                <img class="mb-4" src="{{ asset('storage/' . $blog->gambar) }}" height="200">
            </div>
          <div>
              {!! $blog->deskripsi !!}}
          </div>
        </div>
    </div>
</div>
@stop